# Regresión lineal con scikit-learn

In [21]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("python-ml-course-master/datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [5]:
X = df[feature_cols]
Y = df["Sales"]

In [7]:
estimator = SVR(kernel="linear")
selector = RFE(estimator,2, step=1)
selector = selector.fit(X,Y)

In [8]:
selector.support_

array([ True,  True, False])

In [9]:
selector.ranking_

array([1, 1, 2])

In [12]:
X_pred = X[["TV", "Radio"]]

In [13]:
lm = LinearRegression()
lm.fit(X_pred,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
lm.intercept_

2.9210999124051362

In [15]:
lm.coef_

array([0.04575482, 0.18799423])

In [17]:
lm.score(X_pred,Y)
#Este es el R2

0.8971942610828956