In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
X = np.random.random(90).reshape(30,3)
X

array([[0.41653425, 0.76025423, 0.8151912 ],
       [0.14904963, 0.63035013, 0.82918795],
       [0.04173845, 0.13703814, 0.63966085],
       [0.11062667, 0.85126615, 0.69219971],
       [0.25834147, 0.81835127, 0.05780285],
       [0.89182305, 0.48955007, 0.19290343],
       [0.21079405, 0.61364163, 0.44500699],
       [0.2377079 , 0.06938391, 0.41970244],
       [0.69800908, 0.29328367, 0.87077358],
       [0.25297864, 0.35968283, 0.99343433],
       [0.60953489, 0.54335546, 0.22544419],
       [0.02071272, 0.07074949, 0.92776262],
       [0.85810129, 0.56932306, 0.10874355],
       [0.80660415, 0.10603668, 0.32225769],
       [0.5071087 , 0.56985544, 0.80640918],
       [0.92881652, 0.08432563, 0.39044698],
       [0.30566384, 0.87090974, 0.76320645],
       [0.145963  , 0.56420025, 0.62758983],
       [0.41734793, 0.94149372, 0.98936837],
       [0.88477275, 0.16544674, 0.1933164 ],
       [0.82950905, 0.08872792, 0.70373585],
       [0.65669345, 0.16925457, 0.6795132 ],
       [0.

In [5]:
# supongamos que vamos a formar 2 grupos
# tenemos que seleccionar 2 ptos al azar y diremos que son los centroides
c1 = np.random.choice(range(len(X)))
c2 = np.random.choice(range(len(X)))

In [7]:
 X[c1], X[c2]

(array([0.69800908, 0.29328367, 0.87077358]),
 array([0.25834147, 0.81835127, 0.05780285]))

In [9]:
clust_center = np.vstack([X[c1], X[c2]])
clust_center

array([[0.69800908, 0.29328367, 0.87077358],
       [0.25834147, 0.81835127, 0.05780285]])

# K-means

In [10]:
from scipy.cluster.vq import vq

In [11]:
vq(X,clust_center)

(array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 0]),
 array([0.54806841, 0.64552276, 0.71310371, 0.65219816, 0.        ,
        0.72640299, 0.44056083, 0.68225615, 0.        , 0.46637603,
        0.47651142, 0.71519198, 0.65139991, 0.58968128, 0.34216615,
        0.57240648, 0.70651069, 0.63393916, 0.71624833, 0.71426268,
        0.29502017, 0.23166945, 0.37875968, 0.65467932, 0.26968212,
        0.7673309 , 0.49254361, 0.62011174, 0.59971015, 0.66297917]))

In [12]:
from scipy.cluster.vq import kmeans

In [13]:
kmeans(X,clust_center) # varicentros

(array([[0.51729597, 0.23698931, 0.44451219],
        [0.2735513 , 0.77064411, 0.653347  ]]), 0.394432699334021)

In [14]:
# o podemos directamente decirle el k
kmeans(X,2)

(array([[0.22473856, 0.64789504, 0.64420085],
        [0.69024332, 0.25495413, 0.38437015]]), 0.3867176817233664)