# Implementando nuestro propio ACP en Python

### Paso a paso

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import chart_studio.plotly.plotly as py
from chart_studio.grid_objs import *
import chart_studio.tools as tls
import plotly.graph_objects as ir
tls.set_credentials_file(username='achiola', api_key='UvJk1Uk9IytDxgO8aF7O')

In [2]:
df = pd.read_csv("../../python-ml-course-master/datasets/iris/iris.csv")

In [3]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# 196. Plotly, la librería de gráficos personalizados e interactivos

In [30]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [31]:
X.shape, y.shape

((150, 4), (150,))

In [33]:
traces = []
legend = {0:False, 1:False, 2:False, 3:False}

colors = { 
    'setosa' : 'rgb(255,127,20)',
    'versicolor' : 'rgb(31,220,120)',
    'virginica' : 'rgb(44,50,180)'
}

for col in range(4):
    for key in colors:
        traces.append(ir.Histogram(x=X[y==key, col], opacity = 0.7, xaxis="x%s"%(col+1), 
                                marker=ir.Marker(color=colors[key]), name = key, showlegend=legend[col]))

data = ir.Data(traces)
layout = ir.Layout(barmode="overlay",
               xaxis = ir.XAxis(domain=[0,0.25], title="Logitud Sepalos"),
               xaxis2 = ir.XAxis(domain=[0.3,0.5], title="Anch. Sepalos"),
               xaxis3 = ir.XAxis(domain=[0.55,0.75], title="Log. Petalos"),
               xaxis4 = ir.XAxis(domain=[0.8,1.0], title="Anch. Petalos"),
               yaxis = ir.YAxis(title="Nro. de ejemplares"),
               title = "Distribicion de los ragos")
fig = ir.Figure(data=data, layout=layout)
py.iplot(fig)

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
X_standard = StandardScaler().fit_transform(X)
X_standard

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [37]:
traces = []
legend = {0:False, 1:False, 2:False, 3:False}

colors = { 
    'setosa' : 'rgb(255,127,20)',
    'versicolor' : 'rgb(31,220,120)',
    'virginica' : 'rgb(44,50,180)'
}

for col in range(4):
    for key in colors:
        traces.append(ir.Histogram(x=X_standard[y==key, col], opacity = 0.7, xaxis="x%s"%(col+1), 
                                marker=ir.Marker(color=colors[key]), name = key, showlegend=legend[col]))

data = ir.Data(traces)
layout = ir.Layout(barmode="overlay",
               xaxis = ir.XAxis(domain=[0,0.25], title="Logitud Sepalos"),
               xaxis2 = ir.XAxis(domain=[0.3,0.5], title="Anch. Sepalos"),
               xaxis3 = ir.XAxis(domain=[0.55,0.75], title="Log. Petalos"),
               xaxis4 = ir.XAxis(domain=[0.8,1.0], title="Anch. Petalos"),
               yaxis = ir.YAxis(title="Nro. de ejemplares"),
               title = "Distribicion de los ragos")
fig = ir.Figure(data=data, layout=layout)
py.iplot(fig)

# 197. Los valores y vectores propios de la matriz de covarianzas

### a) Usando matriz de covarianza

In [38]:
mean_vect = np.mean(X_standard, axis=0)
mean_vect

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [39]:
cov_matrix = (X_standard - mean_vect).T.dot((X_standard - mean_vect)) / (X_standard.shape[0] - 1)
cov_matrix

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [40]:
#con NP podríamos haber hecho esto con
np.cov(X_standard.T)

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [41]:
eig_vals, eig_vectors = np.linalg.eig(cov_matrix)
print("Valores propios \n%s"%eig_vals)
print("Vectores propios \n%s"%eig_vectors)

Valores propios 
[2.93808505 0.9201649  0.14774182 0.02085386]
Vectores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


# 198. La matriz de correlaciones y el Singular Value Decomposition

### b) usando matriz de correlaciones

In [42]:
corr_matrix = np.corrcoef(X_standard.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [43]:
eig_vals_corr, eig_vectors_corr = np.linalg.eig(corr_matrix)
print("Valores propios \n%s"%eig_vals_corr)
print("Vectores propios \n%s"%eig_vectors_corr)

Valores propios 
[2.91849782 0.91403047 0.14675688 0.02071484]
Vectores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


### c) Singular value decomposition

In [44]:
u, s, v = np.linalg.svd(X_standard.T)
u

array([[-0.52106591, -0.37741762,  0.71956635,  0.26128628],
       [ 0.26934744, -0.92329566, -0.24438178, -0.12350962],
       [-0.5804131 , -0.02449161, -0.14212637, -0.80144925],
       [-0.56485654, -0.06694199, -0.63427274,  0.52359713]])

In [45]:
s

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [46]:
v

array([[ 1.08239531e-01,  9.94577561e-02,  1.12996303e-01, ...,
        -7.27030413e-02, -6.56112167e-02, -4.59137323e-02],
       [-4.09957970e-02,  5.75731483e-02,  2.92000319e-02, ...,
        -2.29793601e-02, -8.63643414e-02,  2.07800179e-03],
       [ 2.72186462e-02,  5.00034005e-02, -9.42089147e-03, ...,
        -3.84023516e-02, -1.98939364e-01, -1.12588405e-01],
       ...,
       [ 5.43380310e-02,  5.12936114e-03,  2.75184277e-02, ...,
         9.89532683e-01, -1.41206665e-02, -8.30595907e-04],
       [ 1.96438400e-03,  8.48544595e-02,  1.78604309e-01, ...,
        -1.25488246e-02,  9.52049996e-01, -2.19201906e-02],
       [ 2.46978090e-03,  5.83496936e-03,  1.49419118e-01, ...,
        -7.17729676e-04, -2.32048811e-02,  9.77300244e-01]])

# 199. La selección de las componentes principales

## 2) Las componentes principales

In [47]:
for ev in eig_vectors:
    print("La longitud del vector propio es %s"%np.linalg.norm(ev))

La longitud del vector propio es 0.9999999999999997
La longitud del vector propio es 1.0000000000000002
La longitud del vector propio es 1.0
La longitud del vector propio es 0.9999999999999997


In [48]:
eigen_pairs = [(np.abs(eig_vals[i]), eig_vectors[:,i]) for i in range(len(eig_vals))]
eigen_pairs

[(2.938085050199993,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624873,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.1477418210449481,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.020853862176462803,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

In [49]:
eigen_pairs.sort(reverse=True) # Ordenamos

In [50]:
print("Valores propios en orden descendente")
for ep in eigen_pairs:
    print(ep[0])

Valores propios en orden descendente
2.938085050199993
0.9201649041624873
0.1477418210449481
0.020853862176462803


In [51]:
total_sum = sum(eig_vals)
var_exp = [(i/total_sum)*100 for i in sorted(eig_vals, reverse=True)]
var_exp

[72.96244541329986, 22.850761786701774, 3.6689218892828794, 0.5178709107154932]

In [52]:
cum_var_exp = np.cumsum(var_exp)
cum_var_exp

array([ 72.96244541,  95.8132072 ,  99.48212909, 100.        ])

In [53]:
plot1 = ir.Bar(x=["CP %s"%i for i in range(1,5)], y=var_exp, showlegend=False)
plot2 = ir.Scatter(x=["CP %s"%i for i in range(1,5)], y=cum_var_exp, showlegend=True, name="% de varianza explicada acumulada")
data = ir.Data([plot1,plot2])
layout = ir.Layout(xaxis=ir.XAxis(title="Componentes principales"),
                  yaxis=ir.YAxis(title="% de varianza explicada"),
                  title="Porcentaje de variabilidad de cada CPA")
fig = ir.Figure(data,layout)
py.iplot(fig)

In [54]:
W = np.hstack((eigen_pairs[0][1].reshape(4,1),
              eigen_pairs[1][1].reshape(4,1)))
W

array([[ 0.52106591, -0.37741762],
       [-0.26934744, -0.92329566],
       [ 0.5804131 , -0.02449161],
       [ 0.56485654, -0.06694199]])

# 200. La proyección en el subespacio vectorial resultante

In [55]:
Y = X_standard.dot(W)

In [58]:
results = []

for name in ("setosa", "versicolor", "virginica"):
    result = ir.Scatter(x=Y[y==name,0], y=Y[y==name, 1], mode="markers", name=name, 
                        marker=ir.Marker(size=12,line=ir.Line(color='rgba(220,220,220,0.15)', width=0.5),
                                        opacity=0.8))
    results.append(result)

data = ir.Data(results)
layout = ir.Layout(showlegend=True, scene=ir.Scene(xaxis=ir.XAxis(title="Componente Principal 1"),
                                                  yaxis=ir.YAxis(title="Componente Principal 2")))
fig = ir.Figure(data=data,layout=layout)
py.iplot(fig)